const mongoose= require('mongoose');

const movieSchema=mongoose.Schema(
    {
        name:
        {
            type:String,
            required:[true,"Please enter the movie name"],
        },
        poster:
        {
            type:String,
            required:true,
        },
        description:
        {
            type:String,
            required:false,
        },
        director:
        {
            type:String,
            required:false,
        },
        genre:
        {
            type:String,
            required:false,
        },
        rate:
        {
            type:Number,
            required:false,
            default:0,
        },
        duration:
        {
            type:String,
            required:false,
        },
        src:
        {
            type:String,
            required:false,
        },
        c1:
        {
            type:String,
            required:false,
        },
        c2:{
            type:String,
            required:false,
        },
        c3:
        {
            type:String,
            required:false,
        },
        c4:
        {
            type:String,
            required:false,
        },
        c5:
        {
            type:String,
            required:false,
        },
        c6:
        {
            type:String,
            required:false,
        },
        r1:
        {
            type:String,
            required:false,
        },
        r2:
        {
            type:String,
            required:false,
        },
        r3:
        {
            type:String,
            required:false,
        },
        r4:
        {
            type:String,
            required:false,
        }
    }
    ,{
        timestamps:true
    }
)
const Movie=mongoose.model('Movie',movieSchema);
module.exports=Movie;